In [3]:
import numpy as np 
import pandas as pd

### Initial analytics on YOLO results

In [12]:
csv_path = "C:\\Users\\Caroline Wang\\OneDrive\\DSSG\\air_pollution_estimation\\data\\sample_yolo_output\\sample_yolo_output.csv"
yolo_df = pd.read_csv(csv_path)
yolo_df.head(15)

,obj_ind,camera_id,frame_id,date,time,obj_bounds,obj_classification,confidence
0,0,6508,0,2019-06-03,11:45:00,[ 77 186 105 202],car,0.906052
1,1,6508,0,2019-06-03,11:45:00,[189 109 197 119],car,0.602732
2,2,6508,0,2019-06-03,11:45:00,[257 140 311 218],car,0.601965
3,3,6508,0,2019-06-03,11:45:00,[ 18 125 82 163],car,0.524435
4,4,6508,0,2019-06-03,11:45:00,[124 93 174 157],bus,0.521526
5,5,6508,0,2019-06-03,11:45:00,[ 36 133 62 157],car,0.461769
6,6,6508,0,2019-06-03,11:45:00,[329 173 333 189],person,0.443098
7,7,6508,0,2019-06-03,11:45:00,[250 110 258 122],car,0.401753
8,8,6508,0,2019-06-03,11:45:00,[ 2 130 8 146],person,0.374517
9,9,6508,0,2019-06-03,11:45:00,[274 156 300 204],truck,0.309682
10,10,6508,0,2019-06-03,11:45:00,[342 172 346 192],person,0.275270
11,0,6508,1,2019-06-03,11:45:00,[ 78 184 106 200],car,0.890877
12,1,6508,1,2019-06-03,11:45:00,[189 110 197 118],car,0.723662
13,2,6508,1,2019-06-03,11:45:00,[257 140 311 218],car,0.614710
14,3,6508,1,2019-06-03,11:45:00,[ 19 126 81 164],car,0.568334

In [ ]:
yolo_df.drop(["camera_id", "date", "time"])

In [11]:
# yolo_df.groupby("frame_id").groupby("obj_classification").count()
yolo_df["frame_id", "obj_classifications"].groupby("frame_id").count()

KeyError: ('frame_id', 'obj_classifications')